version: '3'
services:
    linuxconsole64-2024:
        image: yledoare/ydfs-2.10
        volumes:
            - $HOME/iso:/home/linuxconsole2024/iso
        environment:
            BUILDYDFS: "fast"
            SLEEPTIME: 1
